services:
  php:
    container_name: php-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
      - redis
    networks:
      - wordpress-network

  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: sandirahasiah
      MYSQL_DATABASE: wordpress_dp
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: sandi_wordpress
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - wordpress-network

  redis:
    image: redis:latest
    container_name: redis-server
    networks:
      - wordpress-network

networks:
  wordpress-network: